name: Build .NET Project for Multiple Platforms

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux-arm64:
      runs-on: ubuntu-20.04
      name: Build for Linux ARM64
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up .NET
          uses: actions/setup-dotnet@v2
          with:
            dotnet-version: '9.0'

        - name: Install ARM64 cross-compilation tools
          run: |
            sudo apt-get update
            sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu binutils-aarch64-linux-gnu
            sudo apt-get install -y clang lld

        - name: Install dependencies
          working-directory: ./MemeFactory/MemeProcessorLibrary
          run: |
            dotnet restore MemeProcessorLibrary.csproj

        - name: Build and publish
          working-directory: ./MemeFactory/MemeProcessorLibrary
          env:
            CC: clang
            CXX: clang++
            LD: ld.lld
          run: |
            dotnet publish MemeProcessorLibrary.csproj -c Release -r linux-arm64 --output ./out --self-contained true

        - name: Upload build artifacts
          uses: actions/upload-artifact@v4
          with:
            name: linux-arm64-build
            path: ./MemeFactory/MemeProcessorLibrary/out

  build-macos-arm64:
    runs-on: macos-latest
    name: Build for macOS ARM64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '9.0'

      - name: Install dependencies
        working-directory: ./MemeFactory/MemeProcessorLibrary
        run: |
          dotnet restore

      - name: Build and publish
        working-directory: ./MemeFactory/MemeProcessorLibrary
        run: |
          dotnet publish -c Release -r osx-arm64 --output ./out

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-arm64-build
          path: ./MemeFactory/MemeProcessorLibrary/out

  build-macos-x64:
    runs-on: macos-latest
    name: Build for macOS x64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '9.0'

      - name: Install dependencies
        working-directory: ./MemeFactory/MemeProcessorLibrary
        run: |
          dotnet restore

      - name: Build and publish
        working-directory: ./MemeFactory/MemeProcessorLibrary
        run: |
          dotnet publish -c Release -r osx-x64 --output ./out

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-x64-build
          path: ./MemeFactory/MemeProcessorLibrary/out