name: Build for Ubuntu ARM64

on:
  workflow_dispatch:

jobs:
  build-ubuntu-arm64:
    runs-on: ubuntu-22.04-arm
    name: Build for Ubuntu ARM64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '9.0'

      - name: Install dependencies
        working-directory: ./MemeFactory/MemeProcessorLibrary
        run: |
          dotnet restore

      - name: Build and publish
        working-directory: ./MemeFactory/MemeProcessorLibrary
        run: |
          dotnet publish -c Release -r linux-arm64 --output ./out

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-arm64-build
          path: ./MemeFactory/MemeProcessorLibrary/out