name: Build for Linux ARM64

on:
    workflow_dispatch:

jobs:
  build-linux-arm64:
    runs-on: ubuntu-20.04
    name: Build for Linux ARM64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Install ARM64 cross-compilation tools
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu binutils-aarch64-linux-gnu
          sudo apt-get install -y clang lld

      - name: Install additional dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zlib1g-dev

      - name: Install dependencies
        working-directory: ./MemeFactory/MemeProcessorLibrary
        run: |
          dotnet restore MemeProcessorLibrary.csproj

      - name: Build and publish
        working-directory: ./MemeFactory/MemeProcessorLibrary
        env:
          CC: clang
          CXX: clang++
          LD: ld.lld
        run: |
          dotnet publish MemeProcessorLibrary.csproj -c Release -r linux-arm64 --output ./out --self-contained true

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-arm64-build
          path: ./MemeFactory/MemeProcessorLibrary/out